"""initial migration

Revision ID: 43f5622c87d4
Revises: 
Create Date: 2026-08-17 10:10:07.418989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43f5622c87d4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('Customer', 'Admin', 'Driver', name='userenum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.Enum('OFF', 'LOCAL', 'FLEXIBLE', 'TRIP', name='drivingmode'), nullable=False),
    sa.Column('local_operating_area', sa.Enum('HEBRON', 'NABLUS', 'RAMALLAH_AND_AL_BIREH', 'JENIN', 'BETHLEHEM', 'JERICHO_AND_AL_AGHwar', 'TULKARM', 'QALQILYA', 'SALFIT', 'TUBAS_AND_NORTHERN_VALLEY', 'JERUSALEM', name='governorate'), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drivers_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_status_change', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'EXPIRED', 'ERROR', name='assignmenapplicationtstatus'), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('route_from', sa.Enum('HEBRON', 'NABLUS', 'RAMALLAH_AND_AL_BIREH', 'JENIN', 'BETHLEHEM', 'JERICHO_AND_AL_AGHwar', 'TULKARM', 'QALQILYA', 'SALFIT', 'TUBAS_AND_NORTHERN_VALLEY', 'JERUSALEM', name='governorate'), nullable=False),
    sa.Column('route_to', sa.Enum('HEBRON', 'NABLUS', 'RAMALLAH_AND_AL_BIREH', 'JENIN', 'BETHLEHEM', 'JERICHO_AND_AL_AGHwar', 'TULKARM', 'QALQILYA', 'SALFIT', 'TUBAS_AND_NORTHERN_VALLEY', 'JERUSALEM', name='governorate'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'ACTIVE', 'COMPLETED', 'EXPIRED', 'ERORR', name='tripstatus'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_owner_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'IN_TRANSIT', 'DELIVERED', 'REJECTED', 'EXPIRED', 'ERROR', name='orderstatus'), nullable=False),
    sa.Column('type', sa.Enum('LOCAL', 'ROUTE', name='ordertype'), nullable=False),
    sa.Column('route_from', sa.Enum('HEBRON', 'NABLUS', 'RAMALLAH_AND_AL_BIREH', 'JENIN', 'BETHLEHEM', 'JERICHO_AND_AL_AGHwar', 'TULKARM', 'QALQILYA', 'SALFIT', 'TUBAS_AND_NORTHERN_VALLEY', 'JERUSALEM', name='governorate'), nullable=False),
    sa.Column('route_to', sa.Enum('HEBRON', 'NABLUS', 'RAMALLAH_AND_AL_BIREH', 'JENIN', 'BETHLEHEM', 'JERICHO_AND_AL_AGHwar', 'TULKARM', 'QALQILYA', 'SALFIT', 'TUBAS_AND_NORTHERN_VALLEY', 'JERUSALEM', name='governorate'), nullable=False),
    sa.Column('address_receive', sa.String(), nullable=False),
    sa.Column('address_delivery', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['order_owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drivers_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'EXPIRED', 'ERROR', name='assignmenapplicationtstatus'), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.Enum('PENDING', 'ACCEPTED', 'IN_TRANSIT', 'DELIVERED', 'REJECTED', 'EXPIRED', 'ERROR', name='orderstatus'), nullable=False),
    sa.Column('new_status', sa.Enum('PENDING', 'ACCEPTED', 'IN_TRANSIT', 'DELIVERED', 'REJECTED', 'EXPIRED', 'ERROR', name='orderstatus'), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=False),
    sa.Column('more_details', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders_history')
    op.drop_table('drivers_assignments')
    op.drop_table('orders')
    op.drop_table('trips')
    op.drop_table('drivers_applications')
    op.drop_table('drivers')
    op.drop_table('users')
    # ### end Alembic commands ###
