"""added operating area to orders

Revision ID: d2cc7f61b1e8
Revises: 43f5622c87d4
Create Date: 2026-08-23 06:53:05.449738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2cc7f61b1e8'
down_revision: Union[str, Sequence[str], None] = '43f5622c87d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_drivers_id'), 'drivers', ['id'], unique=False)
    op.create_index(op.f('ix_drivers_local_operating_area'), 'drivers', ['local_operating_area'], unique=False)
    op.create_index(op.f('ix_drivers_applications_applicant_id'), 'drivers_applications', ['applicant_id'], unique=False)
    op.create_index(op.f('ix_drivers_applications_id'), 'drivers_applications', ['id'], unique=False)
    op.create_index(op.f('ix_drivers_applications_reviewed_by'), 'drivers_applications', ['reviewed_by'], unique=False)
    op.create_index(op.f('ix_drivers_assignments_driver_id'), 'drivers_assignments', ['driver_id'], unique=False)
    op.create_index(op.f('ix_drivers_assignments_id'), 'drivers_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_drivers_assignments_order_id'), 'drivers_assignments', ['order_id'], unique=False)
    op.add_column('orders', sa.Column('operating_area', sa.Enum('HEBRON', 'NABLUS', 'RAMALLAH_AND_AL_BIREH', 'JENIN', 'BETHLEHEM', 'JERICHO_AND_AL_AGHwar', 'TULKARM', 'QALQILYA', 'SALFIT', 'TUBAS_AND_NORTHERN_VALLEY', 'JERUSALEM', name='governorate'), nullable=True))
    op.alter_column('orders', 'route_from',
               existing_type=postgresql.ENUM('HEBRON', 'NABLUS', 'RAMALLAH_AND_AL_BIREH', 'JENIN', 'BETHLEHEM', 'JERICHO_AND_AL_AGHwar', 'TULKARM', 'QALQILYA', 'SALFIT', 'TUBAS_AND_NORTHERN_VALLEY', 'JERUSALEM', name='governorate'),
               nullable=True)
    op.alter_column('orders', 'route_to',
               existing_type=postgresql.ENUM('HEBRON', 'NABLUS', 'RAMALLAH_AND_AL_BIREH', 'JENIN', 'BETHLEHEM', 'JERICHO_AND_AL_AGHwar', 'TULKARM', 'QALQILYA', 'SALFIT', 'TUBAS_AND_NORTHERN_VALLEY', 'JERUSALEM', name='governorate'),
               nullable=True)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_operating_area'), 'orders', ['operating_area'], unique=False)
    op.create_index(op.f('ix_orders_order_owner_id'), 'orders', ['order_owner_id'], unique=False)
    op.create_index(op.f('ix_orders_route_from'), 'orders', ['route_from'], unique=False)
    op.create_index(op.f('ix_orders_route_to'), 'orders', ['route_to'], unique=False)
    op.create_index(op.f('ix_orders_history_changed_by_id'), 'orders_history', ['changed_by_id'], unique=False)
    op.create_index(op.f('ix_orders_history_id'), 'orders_history', ['id'], unique=False)
    op.create_index(op.f('ix_orders_history_order_id'), 'orders_history', ['order_id'], unique=False)
    op.create_index(op.f('ix_trips_driver_id'), 'trips', ['driver_id'], unique=False)
    op.create_index(op.f('ix_trips_id'), 'trips', ['id'], unique=False)
    op.create_index(op.f('ix_trips_route_from'), 'trips', ['route_from'], unique=False)
    op.create_index(op.f('ix_trips_route_to'), 'trips', ['route_to'], unique=False)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_trips_route_to'), table_name='trips')
    op.drop_index(op.f('ix_trips_route_from'), table_name='trips')
    op.drop_index(op.f('ix_trips_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_driver_id'), table_name='trips')
    op.drop_index(op.f('ix_orders_history_order_id'), table_name='orders_history')
    op.drop_index(op.f('ix_orders_history_id'), table_name='orders_history')
    op.drop_index(op.f('ix_orders_history_changed_by_id'), table_name='orders_history')
    op.drop_index(op.f('ix_orders_route_to'), table_name='orders')
    op.drop_index(op.f('ix_orders_route_from'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_owner_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_operating_area'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.alter_column('orders', 'route_to',
               existing_type=postgresql.ENUM('HEBRON', 'NABLUS', 'RAMALLAH_AND_AL_BIREH', 'JENIN', 'BETHLEHEM', 'JERICHO_AND_AL_AGHwar', 'TULKARM', 'QALQILYA', 'SALFIT', 'TUBAS_AND_NORTHERN_VALLEY', 'JERUSALEM', name='governorate'),
               nullable=False)
    op.alter_column('orders', 'route_from',
               existing_type=postgresql.ENUM('HEBRON', 'NABLUS', 'RAMALLAH_AND_AL_BIREH', 'JENIN', 'BETHLEHEM', 'JERICHO_AND_AL_AGHwar', 'TULKARM', 'QALQILYA', 'SALFIT', 'TUBAS_AND_NORTHERN_VALLEY', 'JERUSALEM', name='governorate'),
               nullable=False)
    op.drop_column('orders', 'operating_area')
    op.drop_index(op.f('ix_drivers_assignments_order_id'), table_name='drivers_assignments')
    op.drop_index(op.f('ix_drivers_assignments_id'), table_name='drivers_assignments')
    op.drop_index(op.f('ix_drivers_assignments_driver_id'), table_name='drivers_assignments')
    op.drop_index(op.f('ix_drivers_applications_reviewed_by'), table_name='drivers_applications')
    op.drop_index(op.f('ix_drivers_applications_id'), table_name='drivers_applications')
    op.drop_index(op.f('ix_drivers_applications_applicant_id'), table_name='drivers_applications')
    op.drop_index(op.f('ix_drivers_local_operating_area'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_id'), table_name='drivers')
    # ### end Alembic commands ###
